<a href="https://colab.research.google.com/github/mdNotFound/100-days-of-ai-engineering/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [4]:
scalar.ndim

0

In [5]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
MATRIX2=torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
MATRIX3=torch.tensor([[10,11,12],
                      [13,14,15],
                      [16,17,18]])
x=torch.stack([MATRIX2,MATRIX3])

In [18]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [19]:
x.ndim

3

In [20]:
x.shape

torch.Size([2, 3, 3])

In [21]:
y=torch.tensor([
    [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ],
      [
          [10,11,12],
          [12,13,14],
          [15,16,17]
           ]
      ])
y

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [22]:
y.ndim

3

In [23]:
y.shape

torch.Size([2, 3, 3])

In [24]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9399, 0.1729, 0.1965, 0.4331],
        [0.3790, 0.4778, 0.5490, 0.1293],
        [0.1410, 0.9054, 0.8911, 0.9521]])

In [25]:
random_tensor.ndim

2

In [26]:
random_tensor.shape

torch.Size([3, 4])

In [27]:
random_tensor2=torch.rand(1,10,10)
random_tensor2

tensor([[[0.5456, 0.5440, 0.3695, 0.5762, 0.0620, 0.3165, 0.3188, 0.8904,
          0.4630, 0.9996],
         [0.6634, 0.9937, 0.2913, 0.3960, 0.2262, 0.3955, 0.7552, 0.7232,
          0.8610, 0.7609],
         [0.2115, 0.2855, 0.3706, 0.0759, 0.8786, 0.3700, 0.9263, 0.4832,
          0.7870, 0.0393],
         [0.4857, 0.8852, 0.0984, 0.8909, 0.7715, 0.4556, 0.6535, 0.5073,
          0.2344, 0.2438],
         [0.1893, 0.1094, 0.5732, 0.1769, 0.2218, 0.5390, 0.7123, 0.7515,
          0.6942, 0.9376],
         [0.8464, 0.4073, 0.6526, 0.1710, 0.1348, 0.2710, 0.0624, 0.1613,
          0.8381, 0.7808],
         [0.7117, 0.4404, 0.9588, 0.9185, 0.3137, 0.2219, 0.2919, 0.0485,
          0.5678, 0.2910],
         [0.2285, 0.4696, 0.2184, 0.9195, 0.1131, 0.5099, 0.1680, 0.1637,
          0.3286, 0.1151],
         [0.5574, 0.1222, 0.0819, 0.3303, 0.2241, 0.3881, 0.2783, 0.9120,
          0.1474, 0.3132],
         [0.7899, 0.6220, 0.7567, 0.4618, 0.5735, 0.8668, 0.9457, 0.5739,
          0.6973,

In [28]:
random_tensor2.ndim

3

In [29]:
random_image_tensor=torch.rand(size=(224,224,3))
random_image_tensor

tensor([[[0.2465, 0.1127, 0.6864],
         [0.4972, 0.7635, 0.6257],
         [0.9246, 0.1073, 0.4551],
         ...,
         [0.3035, 0.7108, 0.7125],
         [0.6675, 0.4200, 0.6805],
         [0.7383, 0.8569, 0.5459]],

        [[0.8709, 0.3534, 0.8936],
         [0.2911, 0.0477, 0.4342],
         [0.6517, 0.1086, 0.4202],
         ...,
         [0.5012, 0.5472, 0.5914],
         [0.8322, 0.4257, 0.4646],
         [0.3333, 0.4789, 0.3700]],

        [[0.9580, 0.9443, 0.0643],
         [0.5344, 0.9568, 0.1716],
         [0.6815, 0.2263, 0.4864],
         ...,
         [0.7479, 0.2037, 0.3362],
         [0.3225, 0.7495, 0.0652],
         [0.1319, 0.1476, 0.4523]],

        ...,

        [[0.7566, 0.2655, 0.0143],
         [0.5570, 0.3556, 0.0929],
         [0.6863, 0.7935, 0.3977],
         ...,
         [0.5758, 0.6345, 0.3461],
         [0.8285, 0.0344, 0.1712],
         [0.3979, 0.4808, 0.1319]],

        [[0.5595, 0.2618, 0.1715],
         [0.2871, 0.8241, 0.8087],
         [0.

In [30]:
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [31]:
random_image_tensor2=torch.rand(224,224,3)
random_image_tensor2

tensor([[[0.5553, 0.6653, 0.9016],
         [0.7256, 0.7820, 0.5950],
         [0.7661, 0.8372, 0.1749],
         ...,
         [0.7798, 0.6629, 0.0047],
         [0.1700, 0.9697, 0.6790],
         [0.1602, 0.5475, 0.9636]],

        [[0.4538, 0.7104, 0.0047],
         [0.0529, 0.3286, 0.8099],
         [0.5108, 0.2248, 0.7344],
         ...,
         [0.0454, 0.1780, 0.1547],
         [0.9342, 0.2692, 0.5248],
         [0.4769, 0.2455, 0.4527]],

        [[0.6506, 0.1137, 0.3519],
         [0.5801, 0.8966, 0.2264],
         [0.1726, 0.5513, 0.2862],
         ...,
         [0.8708, 0.0909, 0.0651],
         [0.9762, 0.1912, 0.5027],
         [0.1122, 0.0522, 0.7657]],

        ...,

        [[0.6858, 0.6562, 0.6615],
         [0.7036, 0.3396, 0.3765],
         [0.2526, 0.1748, 0.1708],
         ...,
         [0.5557, 0.3244, 0.0376],
         [0.7925, 0.3763, 0.5086],
         [0.4917, 0.0260, 0.7770]],

        [[0.2664, 0.7983, 0.9809],
         [0.1210, 0.1632, 0.4852],
         [0.

In [32]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [35]:
r=torch.arange(0,10)
r

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [37]:
ten_zeros=torch.zeros_like(r)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
t=torch.tensor([3.0,6.0,9.0])

In [39]:
t.dtype

torch.float32

In [40]:
t2=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)

In [41]:
t2.dtype

torch.float16

In [42]:
t3=torch.tensor([3.0,6.0,9.0],
                dtype=None,
                device=None,
                requires_grad=False)

In [43]:
float16_tensor=t.type(torch.float16)

In [44]:
t2.device

device(type='cpu')

In [45]:
t2+10

tensor([13., 16., 19.], dtype=torch.float16)

In [46]:
t2*10

tensor([30., 60., 90.], dtype=torch.float16)

In [47]:
t2/2

tensor([1.5000, 3.0000, 4.5000], dtype=torch.float16)

In [48]:
t2-10

tensor([-7., -4., -1.], dtype=torch.float16)

In [50]:
torch.mul(t2,10)

tensor([30., 60., 90.], dtype=torch.float16)

In [51]:
torch.add(t2,10)

tensor([13., 16., 19.], dtype=torch.float16)

In [55]:
torch.matmul(t2,t2)

tensor(126., dtype=torch.float16)