<a href="https://colab.research.google.com/github/mdNotFound/100-days-of-ai-engineering/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [4]:
scalar.ndim

0

In [5]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [20]:
MATRIX2=torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
MATRIX3=torch.tensor([[10,11,12],
                      [13,14,15],
                      [16,17,18]])
x=torch.stack([MATRIX2,MATRIX3])

In [21]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [23]:
x.ndim

3

In [24]:
x.shape

torch.Size([2, 3, 3])

In [28]:
y=torch.tensor([
    [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ],
      [
          [10,11,12],
          [12,13,14],
          [15,16,17]
           ]
      ])
y

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [29]:
y.ndim

3

In [30]:
y.shape

torch.Size([2, 3, 3])