<a href="https://colab.research.google.com/github/mdNotFound/100-days-of-ai-engineering/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import torch

In [20]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [21]:
scalar.item()

7

In [22]:
scalar.ndim

0

In [23]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [24]:
vector.ndim

1

In [25]:
vector.shape

torch.Size([2])

In [26]:
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [27]:
MATRIX.ndim

2

In [28]:
MATRIX.shape

torch.Size([2, 2])

In [29]:
MATRIX[0]

tensor([7, 8])

In [30]:
MATRIX[1]

tensor([ 9, 10])

In [31]:
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [32]:
TENSOR.ndim

3

In [33]:
TENSOR.shape

torch.Size([1, 3, 3])

In [34]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [35]:
MATRIX2=torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
MATRIX3=torch.tensor([[10,11,12],
                      [13,14,15],
                      [16,17,18]])
x=torch.stack([MATRIX2,MATRIX3])

In [36]:
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [37]:
x.ndim

3

In [38]:
x.shape

torch.Size([2, 3, 3])

In [39]:
y=torch.tensor([
    [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ],
      [
          [10,11,12],
          [12,13,14],
          [15,16,17]
           ]
      ])
y

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [40]:
y.ndim

3

In [41]:
y.shape

torch.Size([2, 3, 3])

In [42]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0131, 0.9611, 0.2852, 0.7955],
        [0.2375, 0.4791, 0.0343, 0.8274],
        [0.7447, 0.0506, 0.9348, 0.8942]])

In [43]:
random_tensor.ndim

2

In [44]:
random_tensor.shape

torch.Size([3, 4])

In [45]:
random_tensor2=torch.rand(1,10,10)
random_tensor2

tensor([[[0.4802, 0.8556, 0.7446, 0.5343, 0.6069, 0.6809, 0.5004, 0.7765,
          0.5262, 0.7916],
         [0.6457, 0.2591, 0.1032, 0.7171, 0.1391, 0.7279, 0.4811, 0.7261,
          0.3670, 0.5715],
         [0.8415, 0.3509, 0.5564, 0.9576, 0.0685, 0.3460, 0.6130, 0.3235,
          0.3227, 0.3882],
         [0.4048, 0.3191, 0.9423, 0.2396, 0.9003, 0.3088, 0.5516, 0.2839,
          0.3937, 0.0876],
         [0.7970, 0.1929, 0.6976, 0.6748, 0.2721, 0.4421, 0.2191, 0.3772,
          0.9989, 0.3547],
         [0.1245, 0.0894, 0.6497, 0.5950, 0.1473, 0.4307, 0.0124, 0.4622,
          0.8920, 0.9117],
         [0.3755, 0.7154, 0.7856, 0.3487, 0.3726, 0.9962, 0.0306, 0.1535,
          0.2445, 0.1861],
         [0.7326, 0.7874, 0.2895, 0.3932, 0.8946, 0.6495, 0.8098, 0.5557,
          0.5860, 0.3728],
         [0.1388, 0.6691, 0.3154, 0.1850, 0.1885, 0.3099, 0.8873, 0.6032,
          0.4765, 0.6248],
         [0.4920, 0.0575, 0.8851, 0.3990, 0.0502, 0.8649, 0.9311, 0.9466,
          0.4212,

In [46]:
random_tensor2.ndim

3

In [47]:
random_image_tensor=torch.rand(size=(224,224,3))
random_image_tensor

tensor([[[0.2532, 0.7550, 0.7096],
         [0.1733, 0.5747, 0.9121],
         [0.1850, 0.5286, 0.9296],
         ...,
         [0.3202, 0.7590, 0.1096],
         [0.6277, 0.4412, 0.8363],
         [0.5881, 0.0849, 0.4013]],

        [[0.9599, 0.9149, 0.3929],
         [0.7783, 0.8256, 0.9671],
         [0.9760, 0.7147, 0.9632],
         ...,
         [0.1586, 0.7478, 0.9153],
         [0.0458, 0.9971, 0.5975],
         [0.3312, 0.6606, 0.6477]],

        [[0.6490, 0.6413, 0.3496],
         [0.0431, 0.2649, 0.8134],
         [0.8011, 0.3903, 0.4915],
         ...,
         [0.0107, 0.8843, 0.4222],
         [0.4722, 0.3970, 0.7758],
         [0.2420, 0.6278, 0.0932]],

        ...,

        [[0.5194, 0.3962, 0.3232],
         [0.1929, 0.1706, 0.0352],
         [0.8684, 0.1991, 0.0415],
         ...,
         [0.1378, 0.6264, 0.0735],
         [0.6296, 0.4061, 0.4271],
         [0.1785, 0.4730, 0.2818]],

        [[0.7015, 0.9450, 0.2489],
         [0.9654, 0.3984, 0.5082],
         [0.

In [48]:
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [49]:
random_image_tensor2=torch.rand(224,224,3)
random_image_tensor2

tensor([[[0.1352, 0.3720, 0.8611],
         [0.2268, 0.5253, 0.4558],
         [0.9089, 0.4587, 0.5410],
         ...,
         [0.9599, 0.2543, 0.9542],
         [0.2486, 0.7458, 0.6375],
         [0.1590, 0.8959, 0.2443]],

        [[0.6615, 0.1924, 0.1451],
         [0.2433, 0.3120, 0.2010],
         [0.2766, 0.8291, 0.0177],
         ...,
         [0.2475, 0.7594, 0.2312],
         [0.6666, 0.3264, 0.2621],
         [0.3400, 0.3493, 0.4869]],

        [[0.4989, 0.9611, 0.9235],
         [0.5050, 0.1374, 0.2919],
         [0.6636, 0.0890, 0.2484],
         ...,
         [0.7833, 0.3077, 0.9722],
         [0.7407, 0.8063, 0.9304],
         [0.3907, 0.8846, 0.8413]],

        ...,

        [[0.5089, 0.4028, 0.1925],
         [0.8201, 0.6386, 0.8755],
         [0.7509, 0.5251, 0.8298],
         ...,
         [0.8738, 0.0679, 0.6340],
         [0.3907, 0.0487, 0.2982],
         [0.8922, 0.2987, 0.1638]],

        [[0.3027, 0.4078, 0.0046],
         [0.8018, 0.2038, 0.9294],
         [0.

In [50]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [51]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
ones.dtype

torch.float32

In [53]:
r=torch.arange(0,10)
r

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [55]:
ten_zeros=torch.zeros_like(r)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
t=torch.tensor([3.0,6.0,9.0])

In [57]:
t.dtype

torch.float32

In [58]:
t2=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)

In [59]:
t2.dtype

torch.float16

In [60]:
t3=torch.tensor([3.0,6.0,9.0],
                dtype=None,
                device=None,
                requires_grad=False)

In [61]:
float16_tensor=t.type(torch.float16)

In [62]:
t2.device

device(type='cpu')

In [63]:
t2+10

tensor([13., 16., 19.], dtype=torch.float16)

In [64]:
t2*10

tensor([30., 60., 90.], dtype=torch.float16)

In [65]:
t2/2

tensor([1.5000, 3.0000, 4.5000], dtype=torch.float16)

In [66]:
t2-10

tensor([-7., -4., -1.], dtype=torch.float16)

In [67]:
torch.mul(t2,10)

tensor([30., 60., 90.], dtype=torch.float16)

In [68]:
torch.add(t2,10)

tensor([13., 16., 19.], dtype=torch.float16)

In [69]:
t2 @ t2

tensor(126., dtype=torch.float16)

In [70]:
torch.matmul(t2,t2)

tensor(126., dtype=torch.float16)

In [71]:
torch.matmul(torch.rand(2,3),torch.rand(3,2)) ##shape will be 2x2

tensor([[0.6480, 0.7018],
        [0.6603, 0.7129]])

In [72]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

In [73]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [74]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [75]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [76]:
tensor_A.max()

tensor(6)

In [77]:
tensor_A.min()

tensor(1)

In [78]:
tensor_A.type(torch.float32).mean()

tensor(3.5000)

In [79]:
torch.mean(tensor_A.type(torch.float32))

tensor(3.5000)

In [80]:
t3.std()

tensor(3.)

In [81]:
t3.mean()

tensor(6.)

In [82]:
tensor_A.argmin() ##return index of minimum value

tensor(0)

In [83]:
tensor_A.argmax()

tensor(5)

In [84]:
x=torch.arange(1.,10.)
x.shape

torch.Size([9])

In [85]:
x_reshaped=x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [86]:
#view ## if we change this view real one also changes even if both are in different varilable
x.view(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [87]:
torch.stack([x,x,x,x],dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [88]:
torch.stack([x,x,x,x],dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [89]:
y=torch.arange(3,12)
y=y.view(3,3)
y

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [90]:
y.shape

torch.Size([3, 3])

In [91]:
y.squeeze()

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [92]:
x.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [93]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [94]:
y

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [95]:
y.unsqueeze(dim=1)

tensor([[[ 3,  4,  5]],

        [[ 6,  7,  8]],

        [[ 9, 10, 11]]])

In [96]:
y.unsqueeze(dim=0)

tensor([[[ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])

In [97]:
#permute-rearranges the dimesnions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3))
x_original

tensor([[[0.9179, 0.5362, 0.3751],
         [0.1630, 0.8399, 0.3252],
         [0.5603, 0.6188, 0.6985],
         ...,
         [0.9466, 0.4414, 0.7673],
         [0.3504, 0.8420, 0.3163],
         [0.7936, 0.3778, 0.4763]],

        [[0.4929, 0.9319, 0.0928],
         [0.9868, 0.2631, 0.7700],
         [0.0602, 0.2795, 0.3967],
         ...,
         [0.1835, 0.2983, 0.3390],
         [0.9763, 0.6692, 0.8814],
         [0.8170, 0.1374, 0.5771]],

        [[0.8036, 0.4108, 0.2165],
         [0.0896, 0.2744, 0.1135],
         [0.1556, 0.3402, 0.2575],
         ...,
         [0.3361, 0.7545, 0.1579],
         [0.4531, 0.0261, 0.2574],
         [0.0809, 0.5331, 0.5851]],

        ...,

        [[0.5079, 0.5591, 0.6357],
         [0.9013, 0.3382, 0.6219],
         [0.8452, 0.8588, 0.9642],
         ...,
         [0.3132, 0.9804, 0.1708],
         [0.6598, 0.9255, 0.5214],
         [0.2205, 0.5006, 0.4608]],

        [[0.1718, 0.3760, 0.5394],
         [0.4090, 0.5289, 0.4081],
         [0.

In [98]:
x_permuted=x_original.permute(2,0,1)
x_permuted

tensor([[[0.9179, 0.1630, 0.5603,  ..., 0.9466, 0.3504, 0.7936],
         [0.4929, 0.9868, 0.0602,  ..., 0.1835, 0.9763, 0.8170],
         [0.8036, 0.0896, 0.1556,  ..., 0.3361, 0.4531, 0.0809],
         ...,
         [0.5079, 0.9013, 0.8452,  ..., 0.3132, 0.6598, 0.2205],
         [0.1718, 0.4090, 0.0175,  ..., 0.8646, 0.1944, 0.2823],
         [0.5591, 0.0546, 0.7492,  ..., 0.0849, 0.7648, 0.0974]],

        [[0.5362, 0.8399, 0.6188,  ..., 0.4414, 0.8420, 0.3778],
         [0.9319, 0.2631, 0.2795,  ..., 0.2983, 0.6692, 0.1374],
         [0.4108, 0.2744, 0.3402,  ..., 0.7545, 0.0261, 0.5331],
         ...,
         [0.5591, 0.3382, 0.8588,  ..., 0.9804, 0.9255, 0.5006],
         [0.3760, 0.5289, 0.3325,  ..., 0.3371, 0.6921, 0.8560],
         [0.0514, 0.4481, 0.0642,  ..., 0.8886, 0.8996, 0.5926]],

        [[0.3751, 0.3252, 0.6985,  ..., 0.7673, 0.3163, 0.4763],
         [0.0928, 0.7700, 0.3967,  ..., 0.3390, 0.8814, 0.5771],
         [0.2165, 0.1135, 0.2575,  ..., 0.1579, 0.2574, 0.

In [99]:
x=torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [105]:
x.permute(0)

tensor([1, 2, 3])